### ISSUE TITLE
about cmake install rule

### ISSUE THREAD

**Issue by pkestene** [mrnorman/YAKL#73] opened 2022-09-26 20:10 UTC
Hello,

here is a small description of the problem i'm facing.

Let me first note that
1. I include yakl in another embedding project (using cmake FetchContent), and I create a library that depends on yakl (via a `target_link_libraries` call).
2. in the embedding projet, I also create an alias library to yakl:
`add_library(yakl::yakl ALIAS yakl)` to make linking easier.

Now comes the problem: this projet already contains installation rules, and cmake configure step goes into error, because one of the library (that depends on libyakl), now contains a dependency ti an include directory that is actually a sub-dirrectory of the build directory => error from cmake configure is 
```text
CMake Error in _build/_deps/yakl_external-src/CMakeLists.txt:
  Target "yakl" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/pkestene/.../_build/_deps/yakl_external-src;..."

  which is prefixed in the build directory.
```

There is a simple fix to this: change the following lines from yakl top-level CMakeLists.txt :
```cmake
target_include_directories(yakl PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src)
target_include_directories(yakl PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src/extensions)
target_include_directories(yakl PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/external)
```

into 
```cmake
target_include_directories(yakl PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>
  $<INSTALL_INTERFACE:include>)

target_include_directories(yakl PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src/extensions>
  $<INSTALL_INTERFACE:include/extensions>)

target_include_directories(yakl PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/external>
  $<INSTALL_INTERFACE:include>)
```

then in the embedding projet the install rules are happy, but I feel this just a hack; It would be better if yakl would provide is own install rules.

I also feel yakl should a top-level CMakeLists.txt more "standalone", i.e. libyakl should be "linked" to all its own dependencies (e.g. HAVE_MPI is expected to be defined outside of YAKL, but i think it would be better if it was defined e.g. by a cmake option, and libyakl to be linked to MPI::MPI_CXX in case HAVE_MPI is defined.). In the end, yakl could be installed, and third party projet could include it by a `find_package(yakl)`.

**Comment by mrnorman** [comment] 2022-09-26 22:18
Hi Pierre, thanks for creating this Issue. I'm glad you're finding YAKL useful for your project. Do you feel like YAKL has the functionality you need for your project? Also, I'm curious, are you using the Fortran-style aspects of YAKL?

It may take me a bit to fully understand your use case for YAKL. I'd like to iterate on these topics to learn more from your understanding of CMake and learn more about your use case as well. If there are CMake features that enable the current desired behavior in a cleaner way, I'd like to learn more about them.

## Why not make YAKL more like a traditional TPL?

I'll think more on your desire for YAKL to behave like a more traditional TPL. The main reason I encourage the current behavior is that YAKL is > 99% header-only (i.e., only 40 lines out of about 11K lines are in a source file). Unlike most TPLs, YAKL is very tightly integrated with the source flies that use it, meaning the flags used *when compiling the source files using `YAKL.h`* control YAKL's behavior, not the flags used when compiling the 40 lines of code in `YAKL.cpp`. I feel like encouraging use of the `yakl_process_target()` CMake macro reinforces that notion for users. I'd be worried that they'd set some flags when compiling `YAKL.cpp` (which wouldn't actually do anything), but then might ignore those flags when compiling files that use `#include "YAKL.h"`, thinking that linking against libyakl.a is enough to guarantee their desired behavior.

I currently use CPP macros in compiler flags because:
1. It unifies the control of YAKL's behavior between CMake and Makefile approaches, since both are currently used. I could always add a layer of indirection with CMake, but it's not clear to me what that enables that isn't already enabled with the current approach.
2. It simplifies YAKL's CMake concerns. I could ask YAKL to find MPI. But MPI isn't actually used when compiling `YAKL.cpp`, and the user will have *already* done whatever they need to do regarding MPI for the code that uses YAKL header file -- meaning YAKL doesn't really need to do anything additional. It seems easier to ask the user to inform the YAKL header files if MPI is being used, since they're already handling all other MPI concerns in the source files using YAKL.
3. I feel that it allows more flexibility. If I ask the user to control everything through CMake variables, and always add the resulting flags to all C++ files in the target that links against YAKL, what happens if there are C++ files that don't use YAKL, and the user desires different flags for those files in the target using YAKL? For instance, the user might have a source file with C++20 (which isn't generally supported by YAKL) in a non-YAKL cxx file in the same target. That file cannot use `-std=c++17`. I feel like using compiler flag CPP macro defines and allowing the user a choice of `yakl_process_target()` or `yakl_process_cxx_source_files()` macros is more flexible in this regard.

## You're use case

It sounds from your point (1) that you're actually using YAKL **twice** in the same executable: once in an embedding project, and another time in a library. Is that the case? That is not a use case I've planned for thus far, and it comes with some potential complications. If my understanding is correct, is there a reason the two cannot use the same YAKL target? Is one using a different device backend than the other?

FWIW, I have plans to enable the ability to create multiple YAKL CMake targets with different hardware backends in the same executable (using different C++ namespaces as well). I have the sketches down in my mind, but I'm not certain it'll work until I actually try it out.

## Your requested changes

I'll make the changes your requested and make sure it doesn't interfere with current uses of YAKL in other projects. The syntax you're using isn't familiar to me at the moment, so I need to learn more as I implement it.

Thanks again for creating this issue. Let's iterate on the other topics while I work on this.

**Comment by pkestene** [comment] 2022-09-27 06:50
Hi Matt,

thanks for the detail answer.
I agree that embedding yakl just by calling `add_subdirectory` is handy; I also agree that managing compilation flags may be complex when supportting multiple accelerator programming models. 

I currently just exploring the possibility to use the gator fortran module to refactor memory usage in a large fortran code, where there is already some legacy cuda kernels. This fortran code uses a pattern that I don't like, cuda pointers are declared as static pointer on the cuda side; I'd like to fully manage CPU and GPU memory from the fortran side that why I'm interested in yakl.

I'll make a small cmake reproducer to illustrate more clearly the issue.

**Comment by pkestene** [comment] 2022-10-02 14:15
@mrnorman 
I made a small fortran cmake project, to illustrate the problem with install rules, and how the fix mentioned above solve the problem for me.

here's the demo : https://github.com/pkestene/embedding_yakl
there is a readme at top level to illustrate how to reproduce.

Maybe, there is another simpler way to fix the problem ?

**Comment by mrnorman** [comment] 2022-11-11 18:08
Coming back to this now, sorry for the delay. So, it looks like we just need generator expressions that use a relative path for `INSTALL_INTERFACE`.

**Comment by mrnorman** [comment] 2022-11-11 18:21
Is your YAKL different than the main repo? I'm getting this when I try the reproducer:
```bash
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_INSTALL
```

**Comment by mrnorman** [comment] 2022-11-11 18:22
Sorry, disregard that comment (deleted now)

**Comment by mrnorman** [comment] 2022-11-11 22:02
@pkestene , please take a look here: https://github.com/mrnorman/YAKL/blob/mrnorman/allow-install/CMakeLists.txt

Are you good with this branch's changes?

I made your requested changes above plus an `install()` command that installs libyakl.a, the header files, and cmake and make include files to help the user know what flags were used for the install.

```cmake
install(TARGETS yakl)
install(DIRECTORY src/ external/ DESTINATION include
          FILES_MATCHING PATTERN "*.h")
install(CODE "file(WRITE ${CMAKE_INSTALL_PREFIX}/yakl_variables.cmake \"set(YAKL_COMPILER_FLAGS ${YAKL_COMPILER_FLAGS})\nset(YAKL_ARCH ${YAKL_ARCH})\n\")" )
install(CODE "file(WRITE ${CMAKE_INSTALL_PREFIX}/yakl_variables.make \"YAKL_COMPILER_FLAGS := ${YAKL_COMPILER_FLAGS}\nYAKL_ARCH := ${YAKL_ARCH}\n\")" )

```

**Comment by pkestene** [comment] 2022-11-14 13:58
hi @mrnorman 

there is still an issue, see https://github.com/pkestene/YAKL/blob/fix/install_target/CMakeLists.txt#L39

It's is necessary to add ${CMAKE_CURRENT_BINARY_DIR} to `target_include_directories`, if not then fortran module `gator_mod.mod`is not found when linking to alias library `yakl::yakl` (when building yakl as part of the main project).

Regarding the install commands, I was thinking of providing target exports, espiacially for target yakl::yakl` provides a handy way to link (to need to worry about include/link flag, this is taken care of by the alias library). The benefit of this, is that, a 3rd party project that want to use an already install yakl can just 
- setup env variable CMAKE_PREFIX_PATH to point where yakl.cmake is in the install path
- `find_package(yakl)` is all that is needed to use yakl; all public flags will be transitively transferred to all target linking to `yakl::yakl`

On a given system, it also allows to have several yakl installations path, e.g. one for YAKL_ARCH=CUDA, another for e.g OPENMP45; for each install path, the sys admin can setup a modulefile to ease selecting the wanted yakl version.
 
I can make a branch to illustrate that.

**Comment by pkestene** [comment] 2023-01-27 15:40
hi @mrnorman 

just to let you know that I have rebased branch "fix/install_target" on you latest "main", and made an additional commit to improve "make install" target by providing a regular `yakl-config.cmake`. In the end, it allows to use yakl like this:

From a 3rd party cmake-based project : 
```cmake
find_package(yakl)
...
target_link_libraries(my_exe yakl::yakl)
```
All the flags / preprocessor macro like e.g. YAKL_VERBOSE, YAKL_MANAGED_MEMORY are automatically transitively transferred to the build of `my_exe` sources.

It should not interfere with your way of using yakl, by just using add_subdirectory, it is just an alternative way of using it.
I think it would be great to have it your main branch.

**Comment by mrnorman** [comment] 2023-02-16 05:39
PR 85 implements everything except the build config code below, which caused problems with compiler flags (namely optimization flags):

```cmake
if (NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set(DEFAULT_BUILD_TYPE "RelWithDebInfo")
  message(STATUS "Setting build type to '${DEFAULT_BUILD_TYPE}' as none was specified.")
  set(CMAKE_BUILD_TYPE "${DEFAULT_BUILD_TYPE}" CACHE STRING
    "Choose the type of build, options are: Debug, Release, RelWithDebInfo and MinSizeRel." FORCE)
  # Set the possible values of build type for cmake-gui
  set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS
    "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
endif ()
```

embedding_yakl passes as longs as I add the following to `src/CMakeLists.txt1`
```cmake
if (${CMAKE_VERSION} VERSION_GREATER_EQUAL 3.18)
  set_property(TARGET mykernels PROPERTY CUDA_ARCHITECTURES OFF)
endif()
```

**Comment by mrnorman** [comment] 2023-02-16 05:41
Thanks again for the great cmake improvements, and sorry for the long delay in merging. Hopefully it works well for your use case now.

**Comment by mrnorman** [comment] 2023-02-16 06:52
I'm going to close this for now, but if it ends up not working for your use case, please re-open.

**Closed by mrnorman** 2023-02-16 06:52 UTC
Labels: enhancement
